apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  labels:
    app.kubernetes.io/name: notes-backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
        tier: api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: ghcr.io/rahmatullah7866/devsecops-fullstack-portfolio-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_DEBUG
              value: "False"
            - name: DJANGO_ALLOWED_HOSTS
              value: "notes-backend,localhost,127.0.0.1"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /api/notes/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/notes/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend
  labels:
    app.kubernetes.io/name: notes-backend
spec:
  type: ClusterIP
  selector:
    app: notes-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000